### ISSUE TITLE
Yêu cầu - Làm 2 bộ báo giá

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/To_Ho_Tro#13]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn BI**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **26/12/2023**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **26/12/2023**

[DH - Bao gia chu ky so cloud.xlsx](https://github.com/dh-hos/To_Ho_Tro/files/13768303/DH.-.Bao.gia.chu.ky.so.cloud.xlsx)

[DH - Bao gia phan mem canh bao thuoc.xlsx](https://github.com/dh-hos/To_Ho_Tro/files/13768308/DH.-.Bao.gia.phan.mem.canh.bao.thuoc.xlsx)

**Comment by le-an-87** [comment]
@minhduc2it em làm báo giá nhe!

**Comment by minhduc2it** [comment]
Đã ký đủ báo giá
