### ISSUE TITLE
Yêu cầu - Phân quyền theo tài khoản trên module Printer (Nhà thuốc) Bệnh viện Nhi Đồng TPCT (a.Quốc IT)

### ISSUE THREAD

**Issue by ongtrieuhau** [dh-hos/To_Ho_Tro#14]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÔNG TRIỆU HẬU**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **01/04/2023**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **ngay_hoan_thanh**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92003`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BỆNH VIỆN NHI ĐỒNG - TPCT**

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Yêu cầu phân quyền các chức năng thuộc [Bảng kê] trên module Printer (Nhà thuốc) chỉ cho phép những người được cấu hình sử dụng mới vào được kể cả tài khoản thuộc `nhóm Admin`, hay `Admin phân hệ`. Chỉ có tài khoản `admin` mới được phép cấu hình chức năng này.

![image](https://github.com/dh-hos/To_Ho_Tro/assets/58720300/7920e047-adbe-4643-81ae-85e703cd23b0)

@le-an-87  xem phần mềm hiện tại có chức năng này chưa? hoặc có chức năng nào có thể đáp ứng được yêu cầu này thì hỗ trợ nhé, nếu chưa thì lập yêu cầu mới nhé

**Comment by le-an-87** [comment]
alo anh @lqbinh1987 hỗ trợ bv Nhi đồng anh ơi!

**Comment by lqbinh1987** [comment]
để anh làm yc mới
