### ISSUE TITLE
Hỗ trợ - Bệnh viện Trà Cú báo cáo không tiền mặt bị sai

### ISSUE THREAD

**Issue by ongtrieuhau-dh** [dh-hos/To_Ho_Tro#15]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU  YÊU CẦU HỖ TRỢ</h1>  
</div>

#
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Trà Cú**
-  ![nguoi_lien_he](https://img.shields.io/badge/Người%20liên%20hệ-:-blue?style=plastic&logo=github) **IT Tài**

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)
```
```
![image](https://github.com/dh-hos/To_Ho_Tro/assets/155862740/ac8f0046-4ad6-4715-9fc5-9624fafa2bd2)
![image](https://github.com/dh-hos/To_Ho_Tro/assets/155862740/270768e2-b001-4985-9855-eb10373a36b2)

**Comment by le-an-87** [comment]
@chauthanhtra em liên hệ lại bv Trà Cú nhe!
