### ISSUE TITLE
Yêu cầu - Hỗ trợ Medic Miền đông cài database (do nâng cấp ổ cứng)

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/To_Ho_Tro#18]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **01/03/2024**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **01/03/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `74206`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BỆNH VIỆN MEDIC MIỀN ĐÔNG**

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
- Phân công nhân sự hỗ trợ, báo cáo kết quả.
- Đã hẹn phòng khám tối 01/03/2024
```

**Comment by le-an-87** [comment]
nó hẹn 23h mới bắt đầu làm nhe anh. này để em hỗ trợ luôn.

**Comment by le-an-87** [comment]
Đã hỗ trợ xong.
![ảnh](https://github.com/dh-hos/To_Ho_Tro/assets/96155021/8025cf00-6862-497f-972e-181c57845f62)
![ảnh](https://github.com/dh-hos/To_Ho_Tro/assets/96155021/0032714e-0e60-4db3-95a5-3ba229e76a60)
