### ISSUE TITLE
Hỗ trợ - Viết hướng dẫn sử dụng chức năng nhập giấy lưu trú - giấy chuyển Tuyến (có xác nhận trạng thái chuyển tuyến)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/To_Ho_Tro#19]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU  YÊU CẦU HỖ TRỢ</h1>  
</div>

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)
```
Viết hướng dẫn sử dụng chức năng nhập giấy lưu trú - giấy chuyển Tuyến (có xác nhận trạng thái chuyển tuyến) tại module Register.
```
[Module Register](https://gofile.me/78TQg/UxALqDrHh)
* [theo mô tả XML130] (https://github.com/dh-hos/Mo-ta-he-thong/commit/effe5347535fcf32752d256fa539d89468a6a895)
![ảnh](https://github.com/dh-hos/To_Ho_Tro/assets/96155021/e85d0e11-44eb-46a2-a19e-05d903a428a0)

**Comment by le-an-87** [comment]
Em viết hướng dẫn chổ này nhe @chauthanhtra !

**Comment by chauthanhtra** [comment]
ok anh

**Comment by chauthanhtra** [comment]
Hướng dẫn Xác nhận trạng thái chuyển thuyến và lưu trữ giấy xác nhận lưu trú

[DH-09 HDSD Hướng dẫn cập nhật trạng thái chuyển tuyến và Lưu trữ giấy xác nhận lưu trú.docx](https://github.com/dh-hos/To_Ho_Tro/files/14988287/DH-09.HDSD.H.ng.d.n.c.p.nh.t.tr.ng.thai.chuy.n.tuy.n.va.L.u.tr.gi.y.xac.nh.n.l.u.tru.docx)
[DH-09 HDSD Hướng dẫn cập nhật trạng thái chuyển tuyến và Lưu trữ giấy xác nhận lưu trú.pdf](https://github.com/dh-hos/To_Ho_Tro/files/14988289/DH-09.HDSD.H.ng.d.n.c.p.nh.t.tr.ng.thai.chuy.n.tuy.n.va.L.u.tr.gi.y.xac.nh.n.l.u.tru.pdf)

**Comment by chauthanhtra** [comment]
Anh kiểm tra xem cần bổ sung thông tin gì không nha

**Comment by le-an-87** [comment]
1. Điều chỉnh lại tiêu đề: 
CẬP NHẬT TRẠNG THÁI CHUYỂN TUYẾN
LƯU TRỮ GIẤY XÁC NHẬN LƯU TRÚ
thành
HƯỚNG DẪN SỬ DỤNG CHỨC NĂNG NHẬN BỆNH
ĐỐI VỚI BỆNH NHÂN CÓ GIẤY XÁC NHẬN LƯU TRÚ, GIẤY HẸN VÀ GIẤY CHUYỂN TUYẾN.
2. Cập nhật thêm chức năng lưu trữ tập tin chuyển viện. theo [mô tả v6](https://github.com/dh-hos/Mo-ta-he-thong/issues/23#issuecomment-2062950580)
3. Điều chỉnh mục yêu cầu:
 - Đặt điều kiện cập nhật script đầu tiên.
 - Ghi chú Cập nhật tất cả các Script mới hoặc diễn giải khác. 
 -> do không có script nào ghi nhận hỗ trợ chức năng xác nhận trạng thái CT và lưu trữ GXNLT.

**Comment by chauthanhtra** [comment]
Alo anh @le-an-87 
Trường hợp giấy hẹn tái khám hay giấy hẹn lãnh thuốc thì Nơi giới thiệu điền như thế nào bậy anh? do không điền thì không lưu được file
và chỉ được chọn 1 loại giấy chuyển hoặc giấy hẹn để lưu phải không?

![ảnh](https://github.com/dh-hos/To_Ho_Tro/assets/97272332/5ae52669-9c77-405e-935f-22b4184c249c)

**Comment by le-an-87** [comment]
Đúng tuyến hay thông tuyến thì áp dụng theo 4210. em đừng quan tâm chổ đó.
hiện tại chỉ hướng dẫn xác định trạng thái và lưu file thôi.
Trường hợp giấy hẹn thì bv có thể nhập mã bv hẹn.
cứ áp dụng theo mô tả thôi.

**Comment by chauthanhtra** [comment]
Không xác định rõ ràng thì nếu hỏi có giấy chuyển không thì phải chọn cái nào?
Giấy hẹn và giấy lãnh thuốc Nếu nhập nơi giới thiệu là BV đó luôn thì XML4210 gửi lên nó có mã nơi giới thiệu giống mã BV luôn, vậy có đúng không tự BV giới thiệu cho BV luôn?
Để sau này BV có hỏi để biết trả lời chứ

**Comment by le-an-87** [comment]
Hiện tại phần mềm sử dụng như vậy. em có viết được hướng dẫn không?
có thì cứ kiểm tra theo mô tả mà làm.
còn việc em có ý kiến đóng góp hoặc anh giải thích không thỏa đáng thì cứ làm phiếu góp ý gửi lên nhé.

**Comment by chauthanhtra** [comment]
Cập nhật File hướng dẫn nhận bệnh đối với bệnh nhân có giấy xác nhận lưu trú, giấy hẹn và giấy chuyển tuyến.
Anh kiểm tra lại xem được chưa nha.

[DH-09 HDSD Hướng dẫn sử dụng chức năng nhận bệnh đối với bệnh nhân có giấy xác nhận lưu trú, giấy hẹn và giấy chuyển tuyến.docx](https://github.com/dh-hos/To_Ho_Tro/files/15057184/DH-09.HDSD.H.ng.d.n.s.d.ng.ch.c.nang.nh.n.b.nh.d.i.v.i.b.nh.nhan.co.gi.y.xac.nh.n.l.u.tru.gi.y.h.n.va.gi.y.chuy.n.tuy.n.docx)
[DH-09 HDSD Hướng dẫn sử dụng chức năng nhận bệnh đối với bệnh nhân có giấy xác nhận lưu trú, giấy hẹn và giấy chuyển tuyến.pdf](https://github.com/dh-hos/To_Ho_Tro/files/15057185/DH-09.HDSD.H.ng.d.n.s.d.ng.ch.c.nang.nh.n.b.nh.d.i.v.i.b.nh.nhan.co.gi.y.xac.nh.n.l.u.tru.gi.y.h.n.va.gi.y.chuy.n.tuy.n.pdf)

**Comment by le-an-87** [comment]
Ok rồi!
