### ISSUE TITLE
Yêu cầu - Làm bộ báo giá thêm 02 công ty

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/To_Ho_Tro#4]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn BI**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **26/09/2023**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **28/09/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT huyện Thạnh Trị**

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
[DH - Bao gia Kasperky -15-09-2023.docx](https://github.com/dh-hos/To_Ho_Tro/files/12724371/DH.-.Bao.gia.Kasperky.-15-09-2023.docx)
```
[DH - Bao gia Kasperky -15-09-2023.docx](https://github.com/dh-hos/To_Ho_Tro/files/12724371/DH.-.Bao.gia.Kasperky.-15-09-2023.docx)

**Comment by le-an-87** [comment]
Em làm báo giá này nhe @minhduc2it

**Comment by minhduc2it** [comment]
Đã lấy đủ 3 giá
