### ISSUE TITLE
Yêu cầu - Xác nhận lại yêu cầu BV Lao _CT

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/To_Ho_Tro#8]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **03/10/2023**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **ngay_hoan_thanh**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92016`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BỆNH VIỆN LAO & BỆNH PHỔI**

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
![image](https://github.com/dh-hos/To_Ho_Tro/assets/91751241/70c612b5-f9ae-4352-917e-1e01c8d653df)

- Check lại phần mềm có hỗ trợ được chưa? Nếu chưa xác nhận rõ yêu cầu lại dùm anh rồi thực hiện yêu cầu Git nhé @le-an-87 
```

**Comment by le-an-87** [comment]
Để em kiểm tra lại

**Comment by le-an-87** [comment]
![image](https://github.com/dh-hos/To_Ho_Tro/assets/96155021/d49bd941-3e2e-47c1-8684-4813f1bb270d)

Hiện tại mẫu kết quả chưa đáp ứng được theo yêu cầu này anh ơi.
1. Phiếu kết quả vi sinh chưa có Loại bệnh phẩm
2. Các phiếu kết quả có hiển thị BS điều trị nhưng bệnh viện muốn ghi Bác sĩ chỉ định trên phần thông tin khám bệnh của bệnh nhân.
![image](https://github.com/dh-hos/To_Ho_Tro/assets/96155021/65210b3f-0c9e-4526-a5ff-d47d74462479)
