### ISSUE TITLE
Yêu cầu - Hỗ trợ BV Quận 12 - Mở chức năng chỉnh hồ sơ ngoại trú trên Printer

### ISSUE THREAD

**Issue by ongtrieuhau** [dh-hos/To_Ho_Tro#9]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÔNG TRIỆU HẬU**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **31/10/2023**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **ngay_hoan_thanh**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `79029`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Quận 12**

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```

![image](https://github.com/dh-hos/To_Ho_Tro/assets/58720300/fbe6c47b-3f07-4808-9673-1808627d026d)

```
Hỗ trợ theo cập nhật tại đây [Printer v3.23.1031.3](https://github.com/dh-hos/dhg.hospitalprinter/blob/main/Deploy_Tools/CHANGELOG.md)

**Comment by ongtrieuhau** [comment]
Xem giúp anh cái nhé @le-an-87

**Comment by le-an-87** [comment]
Đã mở chức năng cho BV Quận 12!

**Comment by ongtrieuhau** [comment]
Anh Điền nói chưa nhận được @le-an-87 ơi

**Comment by le-an-87** [comment]
anh nhắn em gửi cho ảnh hả. em tưởng anh kêu test.

**Comment by le-an-87** [comment]
để em gửi a Điền.
